languaje: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "12"
git:
  depth: 3
script:
  - yarn test
  - yarn build
deploy:
  skip_cleanup: true
  keep-history: true
  provider: heroku
  api_key: $API_KEY
  app: starwars-planets-searcher
  on:
    branch: master
